Glavin001/atom-beautify

- menus/atom-beautify.cson
atom-beautify
menus/atom-beautify.cson
Use the `atom-workspace` tag instead of the `workspace` class.
Use the `atom-text-editor` tag instead of the `editor` class.
> updating selectors to the new atom API

- menus/atom-beautify.cson
This removes the warning "ContextMenuManager::add has changed to take a single object as its argument. Please see https://atom.io/docs/api/latest/ContextMenuManager for more info." which is one of the messages described in #267
> Updates context-menu to use new api

- src/languages/jsx.coffee
> adds .js to the extensions supported by the jsx language

- examples/simple-jsbeautifyrc/typescript/expected/test.ts
- examples/simple-jsbeautifyrc/typescript/expected/test2.ts
- src/beautifiers/typescript-formatter.coffee
These defaults were in place until 25e2a754d58. Without them, there is an unfortunate lack of whitespace (IMO).
> Enable typescript-formatter defaults.

- README.md
- package.json
- src/beautifiers/index.coffee
Just spotted that in a notification about a missing beautifier, so I thought I'd correct it.
> Fixing faux possessive 'it is' -> 'its', and some small language fixes

- examples/nested-jsbeautifyrc/gherkin/expected/tables.feature
- examples/nested-jsbeautifyrc/gherkin/expected/test.feature
- examples/nested-jsbeautifyrc/gherkin/original/_tables.feature
- examples/nested-jsbeautifyrc/gherkin/original/test.feature
- package.json
- src/beautifiers/gherkin.coffee
- src/beautifiers/index.coffee
- src/languages/gherkin.coffee
- src/languages/index.coffee
This resolves Glavin001/atom-beautify#377
Uses the https://github.com/cucumber/gherkin/tree/master/js node.js
package to use the official Lexer class.
The only known issue I've seen so far is that it does not format
tables properly -- the columns are not resized to match the widest
cell in each column.
> Add Gherkin grammar support

- src/languages/css.coffee
- src/languages/html.coffee
- src/languages/javascript.coffee
- src/languages/python.coffee
- src/languages/ruby.coffee
- src/languages/sql.coffee
Atom's config is not fully supported at the moment. Config like the following is currently ignored:
```cson
"*":
welcome:
showOnStartup: false
linter:
lintOnChange: false
clearOnChange: true
core: {}
".shell.source":
editor:
tabLength: 4
".python.source":
editor:
tabLength: 4
".java.source":
editor:
tabLength: 4
".gfm.source":
editor:
showInvisibles: false
softWrap: true
tabLength: 4
```
atom-beautify currently ignores the language specific tabLength and other settings and uses the default tabLength of 2 in this case. This commit fixes that issue by specifying the scope in the language files.
> add language scopes to atom language config gets

- src/beautify.coffee
This PR updates atom-beautify so that it properly disposes of all its subscriptions by adding [a standard `deactivate` for clean-up](https://atom.io/docs/v1.0.4/hacking-atom-package-word-count#source-code). This should prevent memory leaks when updating the package, allow it to report updates successfully (see https://github.com/atom/settings-view/issues/532), and avoid potential issues with commands not working immediately after an update.
> Properly dispose of event subscriptions

- docs/options.md
- src/languages/html.coffee
Hi !
This PR add a "HTML - Extra liners" field in Settings View. 
See extra_liners option for HTML docs here : https://github.com/beautify-web/js-beautify#css--html
This option is already supported by atom-beautify but you need to edit your config file manually.
> Add extra_liners option from js-beautify in Settings View

- CHANGELOG.md
- package.json
- src/beautifiers/clang-format.coffee
- src/beautifiers/index.coffee
- src/beautifiers/yapf.coffee
clang-format is a semantics-aware C/C++/Objective-C beautifier from clang compiler tool. It produces correct code even for very complicated sources. So this can be an alternative to uncrusify for C/C++/Obj-C.
yapf (Yet Another Python Formatter) is a python formatter using the same format algorithm as clang-format. It's said to produce better looking pep8-conforming code than autopep8. So someone might want it.
This pull request implements two beautifiers for the above code formatters. I have tested it with my own code base and it works fine.
> Add two beautifiers: clang-format and yapf

- docs/options.md
- package.json
- src/beautifiers/csscomb.coffee
- src/languages/css.coffee
Add setting for custom config file path and support for CSON in addition to the standard JSON config.
Signed-off-by: Daniel Bayley <daniel.bayley@me.com>
> Improve CSScomb support

- .travis.yml
In https://github.com/Glavin001/atom-beautify/pull/629 I added a stack build to Travis. This PR will cache the `~/.stack` dir and greatly speed up subsequent runs.
> Travis: cache stack builds

- docs/options.md
- examples/simple-jsbeautifyrc/jsx/expected/test.jsx
- src/beautifiers/prettydiff.coffee
This is to help address #524 and #591. It looks like the docs were a bit out of date when I ran coffee /docs, so there's some extra `clang-format` support noted in there that's unrelated to this change.
> See #524. Added support for methodchain setting in prettydiff.

- src/beautifiers/csscomb.coffee
Instead of using require which caches the result, check if file exists and then use it if it does, otherwise fall back to bundled config.
> Support dynamically reloading custom file .csscomb.json file changes

- docs/options.md
- src/languages/css.coffee
> Fix missing space in "tomarkup"

- docs/options.md
- src/beautifiers/beautifier.coffee
- src/beautifiers/rubocop.coffee
- src/languages/ruby.coffee
add option to specify the path for rubocop in the settings.
The relative beautifier now retrieve the path similarly to how the php-cs-fixer one does.
I tested it and is working correctly on my system.
> Add Optional Path for Rubocop

- .travis.yml
- examples/nested-jsbeautifyrc/.jsbeautifyrc
- examples/nested-jsbeautifyrc/python/expected/test_isort.py
- examples/nested-jsbeautifyrc/python/original/test_isort.py
- src/beautifiers/autopep8.coffee
- src/beautifiers/yapf.coffee
- src/languages/python.coffee
isort is a very useful tool that orders imports. I added the feature to both python formatters.
+ added a ignoreReturnCode: true to yapf run command to fix the empty error I was getting.
> added import sorting using isort + small yapf fix

- .travis.yml
- CHANGELOG.md
- README.md
- appveyor.yml
- docs/options.md
- examples/nested-jsbeautifyrc/elm/expected/test.elm
- examples/nested-jsbeautifyrc/elm/original/test.elm
- package.json
- src/beautifiers/beautifier.coffee
- src/beautifiers/elm-format.coffee
- src/beautifiers/index.coffee
- src/languages/elm.coffee
- src/languages/index.coffee
- test.elm
Hoping I did this the right way. I just followed the example of the merged PR for supporting stylish-haskell.
Caveat: I don't like that the url for elm-format is hard-coded in the .travis.yml file, but the tool is new enough that it doesn't exist in brew yet.
> Add support for Elm

- src/beautifiers/sqlformat.coffee
- src/languages/sql.coffee
The sqlformat tool can preserve identifier and keyword case. This is particularly useful for identifiers in cases where the RDBMS is case sensitive. Arguably it might be useful for SQL keywords too. This patch enables this by adding another option ('unchanged') that does exactly that and defaults to unchanged in the case of identifiers.
> Adds 'unchanged' option to the SQL beautifier

- CHANGELOG.md
- docs/options.md
- package.json
- src/languages/javascript.coffee
I have tested the package locally and the option seems to work fine now.
> [#776] Bump jsbeautify to 1.6.2.  Add support for collapse-preserve-inline

- src/beautifiers/rustfmt.coffee
This is a breaking change for existing rust format users. rustfmt version 0.3.0 or newer is required. 
The older version of rustfmt will error with the message
```
Unrecognized option: 'config-path'.
```
This commit 
- adds the --config-path parameter with the current folder and will load any rust format in the file's path.
- sets the --write-output format to override. This will avoid creating an unnecessary backup of the tmp source file
> Rust - Add ability to read rustfmt.toml

- docs/options.md
- examples/nested-jsbeautifyrc/apex/expected/test.java
- examples/nested-jsbeautifyrc/apex/original/test.java
- package.json
- spec/beautify-languages-spec.coffee
- src/beautifiers/uncrustify/index.coffee
- src/languages/apex.coffee
- src/languages/index.coffee
Include support for Salesforce's Java-like "Apex" language. Language definition is already provided through MavensMate plugin.
> Add Apex language support

- src/beautifiers/phpcbf.coffee
When no phpcbf path is set in config, beautifier throws error. This fixes it.
no
fixing thing I overlooked
> Fix PHPCBF error when path to executable is not set

- CHANGELOG.md
- package.json
- src/beautifiers/yapf.coffee
YAPF configuration files were previously being ignored. This was because the `run` call to yapf was explicitly defining a `--style` flag.
The --style flag accepts different types of input. From their documentation - "accepts one of the predefined styles (e.g., pep8 or google), a path to a configuration file that specifies the desired style, or a dictionary of key/value pairs."
By not explicitly specifying the --style flag, yapf will look for the following in order
1. In the [style] section of a .style.yapf file in either the current directory or one of its parent directories.
2. In the [yapf] secionf of a setup.cfg file in either the current directory or one of its parent directories.
3. In the ~/.config/yapf/style file in your home directory.
This pull request removes the `--style=pep8` …
> Fix yapf style issue

- src/languages/jade.coffee
It seems, what default extension of jade now is `pug`, but atom-beautifier (with `language-pug` package) can't handle `*.pug` files
> allow beatify *.pug files

- src/beautifiers/js-beautify.coffee
Fixes issue #707 by adding Atom-based EOL detection.
Closes issue #707 (which was already closed through miscommunication between projects).
Determines the default line ending based upon the Atom configuration
`line-ending-selector.defaultLineEnding`. If the Atom configuration
indicates "OS Default", the `process.platform` is queried, returning
CRLF for Windows systems and LF for all other systems.
> Fix issue #707 by adding Atom-based EOL detection

- .travis.yml
- CHANGELOG.md
- examples/nested-jsbeautifyrc/ocaml/expected/js-pattern.ml
- examples/nested-jsbeautifyrc/ocaml/original/js-pattern.ml
- package.json
- src/beautifiers/index.coffee
- src/beautifiers/ocp-indent.coffee
- src/languages/index.coffee
- src/languages/ocaml.coffee
Adds support for OCaml language indentation
no
ocp-indent must be installed:
```
brew install ocaml opam
opam install ocp-indent
```
> add ocaml language

- package.json
- src/beautifiers/beautifier.coffee
Fixes the `spawn cmd.exe ENOENT` error on Windows and makes it possible to run various tools again.
Probably #396, #456, #456, #598, #768, and #932. Possibly more.
This change fixed the support of `rustfmt` for me. I did not test it with any other tool like those in the linked issues above.
> Removed cross-spawn dependency

- .travis.yml
- examples/nested-jsbeautifyrc/ruby/expected/test.rb
- examples/simple-jsbeautifyrc/markdown/expected/yaml-front-matter-2.md
- src/beautify.coffee
- Due to changes between atom 1.8 and 1.9 is editor.viewRegistry not availbale,
it has to be changed to atom.views.
- Modified expected results of test for tidy markdown and rubycop. Seems like expected results didn't look right.
- Modified travis test, it couldn't run on linux due to brew "dependency". I moved most of brew installs to apt for linux and added linuxbrew.
#979
One of Travis Linux tests for some reason fails the first time it's run (on ocaml test). After rerunning that test, it passes OK.
> Fix travis tests and atom 1.9 compatibility issue

- src/beautifiers/beautifier.coffee
- src/beautifiers/marko-beautifier.coffee
- src/beautifiers/php-cs-fixer.coffee
Add .php_cs file (php-cs-fixer config file) support to php-cs-fixer beautifier.
...
Yes, #564 
...
1- I was added a `findFile` method, i think we can use this method in other beautifiers which support config file (e.g. rustfmt beautifier).
2- I think will be better if you chose a same coding style guild for all coffee files.
...
> Add .php_cs file support to php-cs-fixer beautifier

- src/beautifiers/beautifier.coffee
- src/beautifiers/clang-format.coffee
- src/beautifiers/rustfmt.coffee
`rustfmt` 0.5 contains an important but [not that obvious fix](https://github.com/rust-lang-nursery/rustfmt/pull/966). This PR allows us to directly feed the editor contents into `rustfmt` from `stdin` and read the beautified contents from `stdout`.
This not just severly improves performance on slower harddrives, but also fixes a very annoying bug with atom-beautify:
Up till now you could not beautify any files containing Rust's module syntax (`(pub) mod some_file_or_directory_name`), since the referenced files can obviously only be found in the actual working directoy and not in the temporary folder used by `atom-beautify`.
#358 or specifically https://github.com/Glavin001/atom-beautify/issues/358#issuecomment-160482164
- To make writing/reading work from stdin/stdout I had to add some …
> Severely improved support for rustfmt 0.5

- src/beautifiers/phpcbf.coffee
If phpcbfPath is an executable then run it instead of running it as an argument to php
Fixes #958 
> run "phpcbf.bat" instead of "php phpcbf.bat"

- src/languages/c.coffee
This allows beautification of h files when you're doing C development
No
This might break the cpp language since it currently uses the "h" extension, I'm not sure
- [N/A] Added examples for testing to [examples/ directory](examples/)
> Added "h" as a extension to the C language

- src/beautifiers/typescript-formatter.coffee
Hi, the typescript formatter was ignoring ident_with_tabs setting and enforcing "space" indent style and tabs-to-spaces conversion. This PR should fix that.
Should close an issue that is mentioned in #910 but separate issue for typescript was not probably created.
There was another bug in typescript library that prevented changing space indented source to tab indented source. This is already fixed, but is not in an official release yet, only in nightly.
- [ x ] Merged with latest `master` branch
> Fix incorrent enforcement of tabs to spaces conversion in typescript

- src/beautifiers/uncrustify/index.coffee
The uncrutify config path was first resolved against the current project folder.
This would `expand-home-dir` to not expand the home folder.
This patch should fix issues #747 and #818.
None
> fixed order of home-dir expansion and project resolution

- src/beautifiers/elm-format.coffee
Changes the help URL for elm-format to the official installation instructions URL.
No
(I'm the maintainer of elm-format)
> Update installation instructions link for elm-format

- src/languages/fortran.coffee
This PR implements beautify compatibility with free-form Fortran files ending in ".F90".
This resolves issue #1036.
Now works for Fortran files ending in ".F90"
> Add "F90" extension

- CHANGELOG.md
- package.json
- src/beautifiers/phpcbf.coffee
This is a fix for issue #893.
There is an issue squizlabs/PHP_CodeSniffer#993 in `phpcbf` where it hangs when waiting for stdin.
The workaround is to close stdin of the child process since it is not being used anyway.
> Fix phpcbf hanging issue by closing stdin

- CHANGELOG.md
- package.json
- src/beautifiers/index.coffee
This implement a warning when the parsing of the `.jsbeautifyrc` fails. It gives the path of the file, and the reasons it failed for JSON and YAML.
It's related to the feature request #1106
To test this, add an error to any `.jsbeautifyrc` file (like an additional comma) and beautify any related file.
> Added notification for both YAML and JSON .jsbeautifyrc parse error

- src/beautifiers/uncrustify/index.coffee
When the configuration for the `uncrustify` config file path has no path
`atom-beautify` had the habit of pre-pending the path to the
file open in the editor pane. This meant that in order to use a
project specific configuration every directory would need to contain
a config file -- unacceptable. This changes the scheme to pre-pend
the path to the project when no path is specified making it possible
to have a single configuration file for an entire project and also
being able to maintain the configuration under source control.
...
...
> Change path to uncrustify config file to be relative to the project rather than the open file.

- src/languages/javascript.coffee
- src/languages/jsx.coffee
Adds language support in JavaScript and JSX for [language-babel](https://atom.io/packages/language-babel).
The following issues mention language-babel (`Babel ES6 JavaScript`) https://github.com/Glavin001/atom-beautify/issues/974, https://github.com/Glavin001/atom-beautify/issues/1018, https://github.com/Glavin001/atom-beautify/issues/888, https://github.com/Glavin001/atom-beautify/issues/144
> Add JavaScript and JSX language support for language-babel grammar.

- CHANGELOG.md
- package.json
- src/beautifiers/remark.coffee
Updates atom-beautify to use `remark`'s new API.
...
Fixes #1196 
...
...
> Fix remark6.0.1

- README-template.md
Changes some of the links in the `README-template.md` to be relative links.
Some links in the README link to fork's of the project instead of the project's own files.
https://github.com/blog/1395-relative-links-in-markup-files
http://stackoverflow.com/questions/23789542/github-link-to-wiki-page-from-readme
...
No issues are closed by this.
...
See [here](https://github.com/Glavin001/atom-beautify/compare/master...vmuriart:master#diff-f2f6b54f161da233f703d03e5ac97812L140) for an example.
...
> Use relative links in README/README-template

- .travis.yml
Improve/fix builds on Travis CI @ mac !
For example see: https://travis-ci.org/Glavin001/atom-beautify/jobs/168139151#L233
"**Error**: python-2.7.12_1 already installed"
> remove python from mac installation

- src/beautifiers/js-beautify.coffee
I would love to use the **language-babel** syntax package and **JS Beautify** together for my **js** files, this will make it possible!
> Add JSX option to to JS Beautify

- src/beautifiers/js-beautify.coffee
When i tried to beautify **EJS** or **JSX** with JS Beautify, it wont work, because i forgot to add **EJS** and **JSX** on the **Switch** when i added it to **JS Beautify** options. This will fix the issue.
> Fix JS beautify on JSX and EJS

- src/beautifiers/index.coffee
This fixes the "extname is deprecated" issue.  It happens when you try to beautify a file that is not saved, so when trying to fetch the extension, the code passes a null filename to get the extension, and causes this error.
This closes #1423
No other comments
> Fix #1423 - extname is deprecated

- src/beautifiers/php-cs-fixer.coffee
`PHP-CS-Fixer Path` option is not enable except Windows. So fixed.
No, it doesn't.
And few refactored.
> Fix php cs fixer path option except windows

- package.json
Because 2.0.5 is broken
Related to #1549
> use tidy-markdown 2.0.3 explicitly

- src/beautifiers/vue-beautifier.coffee
objective
-------------
only `<template><script><style>` at beginning of line will mark sections of vue file
before
-------------
with src/beautifiers/vue-beautifier.coffee as now
```coffee
beautify: (text, language, options) ->
return new @Promise((resolve, reject) ->
regexp = /(<(template|script|style)[^>]*>)((\s|\S)*?)<\/\2>/gi
```
will format vue code as bad
```vue
<template>
<div>
<template>
</template>
</div>
</template>
<script>
var str = '<script>
</script>'
</script>
```
after
--------
with src/beautifiers/vue-beautifier.coffee as now
```coffee
beautify: (text, language, options) ->
return new @Promise((resolve, reject) ->
regexp = /(^<(template|script|style)[^>]*>)((\s|\S)*?)^<\/\2>/gim
```
will format vue code as right
```javascript
<template>
<div>
<template> </template> …
```
> vue section mark right

- src/beautifiers/autopep8.coffee
- src/beautifiers/yapf.coffee
Hi,
Currently the isort implementation in the python beautifiers (yapf and autopep8) does not take the project configuration into consideration because it runs on a tempfile which makes isort kind of useless if the project have specific configurations for it.
This pull request sets the path for isort to look for the configuration to the project path, if there is no configuration in the project path isort will automatically falls back to the default behavior so this change does not affect who is already using it but fix the behavior for those who have project specific configurations.
Thanks,
> Get isort configuration from project

- docs/options.md
- src/beautifiers/php-cs-fixer.coffee
- src/languages/php.coffee
- src/options.json
...
Closes https://github.com/Glavin001/atom-beautify/issues/1607
...
> See #1607. Add support for PHP-CS-Fixer 1, along with version 2.

- docs/options.md
- src/beautifiers/php-cs-fixer.coffee
- src/languages/php.coffee
- src/options.json
Adds an option for allow-risky in php-cs-fixer so you can apply risky rules if you want to.
I am not sure.
none.
> php-cs-fixer allow risky option

- docs/options.md
- script/build-options.js
- src/options.json
When an option doesn't have a description `undefined` prefixes the `(Supported by ...)` declaration in the settings
> fix `undefined` when options has no description

- docs/options.md
- src/beautifiers/php-cs-fixer.coffee
- src/beautifiers/phpcbf.coffee
- src/languages/php.coffee
- src/options.json
This adds a setting to PHP for the PHPCBF Version.
If the PHPCBF version is 3 than it removes the `--no-patch` flag
#1643
The setting is defaulted to 2 so it doesn't change the current behavior
> Add PHPCBF Version setting

- CHANGELOG.md
- src/languages/yaml.coffee
This fixes https://github.com/Glavin001/atom-beautify/issues/1647 .
> Set default padding to 0, not null

- src/beautifiers/phpcbf.coffee
Adds `.php` extension to the temp file that is created for PHPCBF
PHPCBF v3.0 will filter out and files without the `.php` extension by default. Alternatively we could tell it not to filter out the files but i felt adding the `.php` extension is easier and will help reduce errors in the future.
> add .php extension to temp files

- src/beautifiers/phpcbf.coffee
#1643 only fixed Windows. This applies the same fix to other platforms.
#1682
> Fix #1682. Removed --no-patch flag from phpcbf beautifier version 3

- CHANGELOG.md
- docs/add-languages-and-beautifiers.md
- docs/options.md
- src/beautifiers/php-cs-fixer.coffee
- src/languages/php.coffee
- src/options.json
This PR adds a PHP-CS-Fixer setting to specify a custom config file. If no setting is provided, it checks first the working directory then the project root for `.php_cs` and `.php_cs.dist` and uses whichever it finds first.
I also updated the example link to PHP-CS-Fixer source in `add-languages-and-beautifiers.md` to account for the additions, and fixed the capitalization in the "Allow risky rules" setting description.
[#1524](https://github.com/Glavin001/atom-beautify/issues/1524), part of [#1537](https://github.com/Glavin001/atom-beautify/issues/1537), possibly [#915](https://github.com/Glavin001/atom-beautify/issues/915).
This has only been tested on PHP-CS-Fixer version 2.3.1 on OS X, though it's unlikely to behave differently on PHP-CS-Fixer 1.x or Windows.
Check all those that are …
> Improve PHP-CS-Fixer config file support

- CHANGELOG.md
- README.md
- src/languages/latex.coffee
- src/options.json
Adds LaTeX extensions `.bib`, `.sty`, `.cls`, `.dtx`, `.ins`, `.bbx` and `.cbx`.
No.
No.
> Add more LaTeX extensions

- README.md
- src/languages/perl.coffee
Add more perl filetypes
...
No
...
Separate issue but your perltidy test examples/simple-jsbeautifyrc/perl/expected isn't actually perltidy'd. 
...
> Add more perl filetypes

- docs/options.md
- examples/simple-jsbeautifyrc/lua/expected/test.lua
- examples/simple-jsbeautifyrc/lua/original/test.lua
- src/beautifiers/lua-beautifier/beautifier.coffee
- src/beautifiers/lua-beautifier/index.coffee
- src/languages/lua.coffee
- src/options.json
- add scientific notation support
- add EOL support
- add option to control whether adjust whitespace
#1613 and #1588
> Fixed #1613 and #1588. Add EOL, scientific notiation, and adjust whitespace support

- CHANGELOG.md
- src/beautifiers/rubocop.coffee
Rubocop was excluding files  passed to it without a proper extension even if
they are passed as command line parameters. This adds a `.rb` to the filename
used for the temp files so they are always detected.
#1652 and #1653 (they are duplicates).
Examples don't need to change, should be completely transparent.
> Add `.rb` to temp files passed to `rubocop`

- CHANGELOG.md
- README.md
- docs/options.md
- package.json
- src/beautifiers/goimports.coffee
- src/beautifiers/index.coffee
- src/options.json
This adds goimports beautifier for Go language.
...
...
> Add goimports beautifier for Go language

- CHANGELOG.md
- spec/atom-beautify-spec.coffee
- src/beautifiers/beautifier.coffee
- src/beautifiers/executable.coffee
Shorten the error message when Executable command is not found.
Hopefully a bunch of related question issues asking what "Could not find X" means.
...
> Improve command not found error message

- src/beautifiers/latex-beautify.coffee
The new latex indent v3.2.2 has fixed the [issue #1564](https://github.com/Glavin001/atom-beautify/issues/1564#issuecomment-311768474), but it changes its flag order as mentioned by @cmhughes:
> I think I see the problem: the -o switch changed a little bit in v3.0 of latexindent.pl, and needs the output file to be specified next to the -o switch, for example:
latexindent.pl myfile.tex -o output.tex
So, if you move the -o switch in between the two @texfile statements, that might work.
Yes, it closes [issue #1564](https://github.com/Glavin001/atom-beautify/issues/1564#issuecomment-311768474).
@cmhughes suggested to use 
```shell
latexindent.pl myfile.tex -w
```
instead of 
```shell
latexindent.pl myfile.tex -o myfile.tex
```
maybe we can consider it as an option in the settings menu.
Check …
> Fix for latexindent v3

- CHANGELOG.md
- README.md
- docs/code/class/Rustfmt.html
- docs/code/extra/README.md.html
- src/beautifiers/rustfmt.coffee
This PR enables running newish rustfmt tool (known as rustfmt-nightly).
Its version numbering scheme has been restarted from 0.1.0.
To whitelist these new builds, the version regex was changed to only trigger when the version numbers are NOT followed by `-nightly` suffix.
See #358 
> Rustfmt nightly

- src/beautify.coffee
Fix to handle the async save operation of editor.save() released in Atom 1.19. Resolves promise from editor.save before deleting pendingPaths and logging it.
https://github.com/Glavin001/atom-beautify/issues/1721 and https://github.com/Glavin001/atom-beautify/issues/1801
First pull request ever on GitHub, please provide any feedback on improvements.
> Fix for #1721

- src/beautifiers/executable.coffee
Fixes deprecation warnings for os.tmpDir() changing to os.tmpdir()
...
#1833 
...
...
> Fix deprecation warning closing #1833

- .travis.yml
Homebrew requires Ruby 2.3 to run.  The Travis images for OSX are outdated, and the only way to get Homebrew working is to run `brew update` before doing anything else, as suggested in https://github.com/Homebrew/brew/issues/3299.
...
...
...
> Run brew update as suggested workaround for Ruby version issue

- CHANGELOG.md
- package.json
- src/beautifiers/executable.coffee
Docker for Mac's current version is:  `Docker version 17.09.0-ce, build afdb6d4`.  Atom Beautify is failing to run Docker images because the regex expects a number between 1-9 for the major, minor, and patch versions of semver.  So when the above is run against match on https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/executable.coffee#L382, it fails because of the `.0`.
This fix allows 0 for both the minor and patch versions.  I don't expect the major version number for Docker to ever be 0, so no change there.
...
#1888 
...
...
> Allow 0 for minor and patch versions of docker

- .gitignore
- .npmignore
- README.md
- menus/atom-beautify.json
- package.json
- tsconfig.json
- Updates Typescript dependency
- If using Atom and the atom-typescript package, saving .ts files in src will compile them into .js files in lib (from change in tsconfig.json)
- Ignore lib directory in git
- Ignore src directory in npm
- Add Atom Beautify to the top menu
...
...
...
> Add lib to gitignore, src to npmignore, package.json & tsconfig updates

- .travis.yml
- CHANGELOG.md
- menus/atom-beautify.cson
- package.json
- src/beautify.coffee
This adds an option to the Packages -> Atom Beautify submenu, Settings, that goes directly to the settings page for Atom Beautify.  This is also available in the command palette.
During the initial Travis build, Rubocop could not be installed on the OSX build because it requires Ruby 2.1 or greater.  The default is 2.0.0, thus a second change was added to use Ruby 2.1.10 so that the Travis build would pass (although it didn't fully, more on that below).
...
#1869 
...
The OSX Travis build will still fail.  I'm getting the same errors with puppet-lint and sass as the master branch here.  I'm still working with Travis support to try and resolve them, but the builds will continue to fail for now.  Since it doesn't fail until the very end, and the Linux builds are fine, it should be safe to …
> Add settings option to menu and use Ruby 2.1.10 in Travis

- package.json
- src/beautify.coffee
Refactors the `handleSaveEvent` function in `beautify.coffee` to make use of `onWillSave` now allowing async operations.  It no longer waits for a save to complete before beautifying and then saving again, instead beautifies when the user invokes a save and afterwards the buffer saves.
...
#1895 
...
Would like some help testing this before it's considered for merging.
...
> Refactor handleSaveEvent to use onWillSave async

- .travis.yml
- appveyor.yml
Travis no longer includes pip in its images.  This fixes the build error to use pip2 instead.
...
#1987 
...
...
> Use pip2 for OSX, php 7.2 for Windows

- CHANGELOG.md
- README.md
- docs/options.md
- examples/simple-jsbeautifyrc/tsx/expected/test.tsx
- examples/simple-jsbeautifyrc/tsx/original/test.tsx
- package.json
- src/beautifiers/typescript-formatter.coffee
- src/languages/index.coffee
- src/languages/tsx.coffee
- src/options.json
Updates typescript-formatter to latest version, along with necessary change in coffeescript file. Also adds support for TSX language and typescript-formatter ability to format it.
...
#601 #1977
...
...
> Update typescript-formatter and add tsx support

- docs/options.md
- examples/nested-jsbeautifyrc/vhdl/expected/test.vhd
- examples/nested-jsbeautifyrc/vhdl/original/test.vhd
- package.json
- src/beautifiers/index.coffee
- src/beautifiers/vhdl-beautifier/emacs-vhdl-formating-script.lisp
- src/beautifiers/vhdl-beautifier/index.coffee
- src/languages/index.coffee
- src/languages/vhdl.coffee
- src/options.json
Added VHDL Support via Emacs. (Analog to Fortran Support)
...
...
> Added VHDL Support via Emacs

- CHANGELOG.md
- src/beautifiers/beautysh.coffee
- src/languages/bash.coffee
- src/options.json
This change adds the ability to indent shell scripts with tabs. It does so by running beautysh with "-t" flag.
Closes https://github.com/Glavin001/atom-beautify/issues/1951
> Added the option to indent Bash scripts with tabs

- package.json
- script/build-options.js
Changes the package requirement of `coffee-script` to `coffeescript`.  No version change, just syntax as the former is deprecated.
...
...
...
> Change from coffee-script to coffeescript for npm package

- CHANGELOG.md
- README.md
- docs/options.md
- package.json
- src/beautifiers/eslint.coffee
- src/options.json
just add an Eslint Fixer beautifier option to support Vue language.
...
#2026 
...
Eslint can not only support *.js files but also *.vue files using plugins such as [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue).
The users can use Eslint Fixer beautifier for vue by setting eslint can handle vue files.
...
> Add Vue support to ESLint Fixer beautifier

- src/beautifiers/prettier.coffee
With the implementation of prettier, I didn't pass the parser into the options properly so it can't beautify anything other than javascript.  This fixes so it works with other supported languages.
...
Closes #2070 
...
...
> Fix to send parser to prettier API properly

- CHANGELOG.md
- src/beautifiers/sqlformat.coffee
For sqlparse-0.2.3 and sqlparse-0.2.4, beautifying sql will throw "sqlformat: error: argument -r/--reindent: ignored explicit argument". I remove the param asignment in the argument and change if condition.
No.
The code works with user's config about "Reindent" in settings->atom-beautify->sql and I hava tested it in both Ubuntu and Windows.
It is the first time I use Travis CI. It passed linux and failed osx, saying "Couldn't set selectedTextBackgroundColor".
> Fix "Reindent" option for sqlformat.

- CHANGELOG.md
- src/beautifiers/executable.coffee
- src/beautifiers/php-cs-fixer.coffee
- Optional Executables do not attempt to use Docker when not installed.
- PHP-CS-Fixer does not work with Docker Executable
No, I do not think so.
See #1707.
> Fix Docker Executable with optional Executable, PHP-CS-Fixer

- src/beautifiers/rubocop.coffee
Fixes an issue with Rubocop and Windows
...
Closes #2092 
...
This is an ugly hack, sorry.  But `os.EOL` doesn't work for all cases.
...
> Workaround for Rubocop string split for Windows

- src/beautifiers/phpcbf.coffee
Requires the `path` library in phpcbf.coffee as path is being used but isn't required, thus causing an error.  Also adds the `optional` flag to PHPCBF executable.
...
Closes #2140 
...
...
> Require path in phpcbf

- CHANGELOG.md
- README-template.md
- src/beautifiers/executable.coffee
Fixes the error being shown to users running executables to be that of the executable, not Docker.
...
Closes #2146 
...
...
> Fix to show executable error instead of Docker

- appveyor.yml
Appveyor Failures.
1. Used Ruby 2.4 64 bit.  Appveyor defaults to 1.9.3.  Why, I don't know.  I suggest 2.5, but pre-compiled gems may be limited.
2. Updated RubyGems.  The RubyGems/Bundler issue should be fixed in the next release, this gets it passing until then.
Haven't looked
I ended up here due to an open issue in another repo.  I just got the tests to pass, haven't even read the README page.
> Appveyor - Ruby 2.4-x64, gem update --system

- README.md
- docs/options.md
- package.json
- src/beautifiers/index.coffee
- src/beautifiers/ocamlformat.coffee
- src/options.json
Adds an alternative formatter for OCaml.
Nope.
I followed the steps [here](https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md) except the 4th one -- I'm not sure how to add tests for this. https://github.com/Glavin001/atom-beautify/tree/master/examples/nested-jsbeautifyrc/ocaml already includes a test case for ocp-indent and I couldn't figure out to create one for ocamlformat.
> Add `ocamlformat` formatter for OCaml.

- CHANGELOG.md
- src/beautifiers/executable.coffee
https://github.com/Glavin001/atom-beautify/issues/2204
You can use the following to clean up:
```bash
docker ps --all | grep "unibeautify/" | awk '{ print $1 }' | xargs docker rm
```
> Fix #2204. Auto-remove docker containers after run.

- package-lock.json
- package.json
-   Bump lodash from 4.17.10 to 4.17.13
-   Bump extend from 3.0.1 to 3.0.2
-   Bump handlebars from 4.0.11 to 4.1.2 
-   Bump open from 0.0.5 to 6.0.0
> Upgrade vulnerable Dependencies
