Glavin001/atom-beautify

- CHANGELOG.md
- examples/nested-jsbeautifyrc/mustache/expected/test.mustache
- lib/language-options.coffee
- package.json
Been waiting for this moment for a couple of weeks now. This new option will finally let me have my angular html templates formatted the way I want, with one attribute per line.
> Updated options for js-beautify

- lib/langs/php-beautify.coffee
I don't have a windows machine to test on, but its a pretty simple command so it should work. Hopefully someone with a Windows machine can test this.
> Add check for Windows and use windows specific 'mv' command

- lib/langs/markdown-beautify.coffee
"Markdown pandoc path" option is not working.
> Fix incorrect name for pandoc path option

- src/beautifiers/typescript-formatter.coffee
fixing this [#351](https://github.com/Glavin001/atom-beautify/issues/351)
> fix typescript support

- src/beautifiers/ruby-beautify.coffee
Hi, fist pull request. It is not working with ruby-beautify. 
Thanks.
> Adjust option name to work with ruby-beautify

- .travis.yml
- README.md
- appveyor.yml
- package.json
- spec/beautify-languages-spec.coffee
- src/beautifiers/prettydiff.coffee
- src/languages/index.coffee
- src/languages/svg.coffee
> Add SVG support

- src/beautifiers/prettydiff.coffee
> Default prettydiff comments to indent

- .travis.yml
- README.md
- examples/nested-jsbeautifyrc/haskell/expected/test.hs
- examples/nested-jsbeautifyrc/haskell/original/test.hs
- src/beautifiers/index.coffee
- src/beautifiers/stylish-haskell.coffee
- src/languages/haskell.coffee
- src/languages/index.coffee
fixes https://github.com/Glavin001/atom-beautify/issues/628
> Support stylish-haskell

- src/beautifiers/yapf.coffee
Addressing issue [#669](https://github.com/Glavin001/atom-beautify/issues/669). Tested, and confirmed working!
> Set ignoreResponseCode to true in yapf.coffee

- src/languages/xtemplate.coffee
Adding support for new HTML based template language XTemplate per issue: https://github.com/Glavin001/atom-beautify/issues/746
> Adding support for new HTML templating language: XTemplate

- src/languages/riotjs.coffee
Adding new language Riot.js per issues: https://github.com/Glavin001/atom-beautify/issues/731 and https://github.com/Glavin001/atom-beautify/issues/750
> Adding language Riot.js

- src/languages/xml.coffee
This request is a proposed resolution for https://github.com/Glavin001/atom-beautify/issues/755
> adding XHTML file extension as an XML grammar

- src/languages/xml.coffee
Per https://github.com/Glavin001/atom-beautify/issues/762
> adding support for grammar SLD

- README.md
- src/beautifiers/erl_tidy.coffee
- src/beautifiers/index.coffee
- src/languages/erlang.coffee
- src/languages/index.coffee
Preliminary erlang support. Not sure how I can get erlang to show in the settings though.
Tests will follow
> added erlang support

- docs/options.md
- src/beautifiers/prettydiff.coffee
Added ternaryline option from pretty diff and corresponding documentation.
> Added pretty diff ternaryline option - Issue 524

- README.md
- examples/nested-jsbeautifyrc/d/expected/test.d
- examples/nested-jsbeautifyrc/d/original/test.d
- spec/beautify-languages-spec.coffee
- src/beautifiers/dfmt.coffee
- src/beautifiers/index.coffee
- src/languages/d.coffee
This PR adds basic dfmt support.
> Adding dfmt support for D

- docs/options.md
- examples/nested-jsbeautifyrc/.jsbeautifyrc
- examples/nested-jsbeautifyrc/.jsbeautifyrc_json
- package.json
- src/beautifiers/index.coffee
- src/beautifiers/phpcbf.coffee
- src/beautifiers/remark.coffee
- src/languages/markdown.coffee
- src/languages/php.coffee
Quick support for phpcbf related to issue https://github.com/Glavin001/atom-beautify/issues/343
> PHPCBF (PHP_CodeSniffer) + Remark for Markdown support

- src/languages/apex.coffee
> Include Apex extension: "trigger"

- .travis.yml
- build-package.sh
> add stable and beta builds to travis

- examples/nested-jsbeautifyrc/riotjs/expected/test.tag
- examples/nested-jsbeautifyrc/riotjs/original/test.tag
> riotjs tests added

- examples/nested-jsbeautifyrc/opencl/expected/test.cl
- examples/nested-jsbeautifyrc/opencl/original/test.cl
- src/languages/c.coffee
OpenCL language support is achieved here simply by attaching '.CL'
extension to the 'C' language module. OpenCL is C based however beautify
will not support beautification despite having C language support, due
to the different file extension.
https://github.com/Glavin001/atom-beautify/issues/870
> Added opencl language support

- CHANGELOG.md
- docs/options.md
- examples/nested-jsbeautifyrc/latex/expected/test.tex
- examples/nested-jsbeautifyrc/latex/original/test.tex
- package.json
- src/beautifiers/index.coffee
- src/beautifiers/latex-beautify.coffee
- src/languages/index.coffee
- src/languages/latex.coffee
Adds LaTeX language support using [latexindent.pl](https://github.com/cmhughes/latexindent.pl). 
Implements #384.
I am not able to run tests because I don't have all of the beautifying software installed.
> Adds LaTeX language support

- src/beautify.coffee
> Fix deprecation warnings triggered by TextEditor methods

- .travis.yml
- CHANGELOG.md
- README.md
- appveyor.yml
- examples/simple-jsbeautifyrc/lua/expected/test.lua
- examples/simple-jsbeautifyrc/lua/original/test.lua
- package.json
- spec/beautify-languages-spec.coffee
- src/beautifiers/index.coffee
- src/beautifiers/lua-beautifier/beautifier.pl
- src/beautifiers/lua-beautifier/index.coffee
- src/languages/index.coffee
- src/languages/lua.coffee
Adds a perl script beautifier for lua, by @pkulchenko
Fixes #161 
Edit: So I am not sure how this plays around with settings in atom-beautify, so if the developers of this package could check this.
> Lua beautifier

- src/languages/xml.coffee
Adds `.gsp` file support
[#509](https://github.com/Glavin001/atom-beautify/issues/509)
> Added .gsp file extension

- src/beautifiers/beautifier.coffee
fixes #1054 and probably lots of other issues
> check for env.path case-insensitive in windows

- src/beautifiers/js-beautify.coffee
- src/languages/css.coffee
https://github.com/Glavin001/atom-beautify/issues/1077
> Issue #1077

- src/languages/html.coffee
Updates HTML.unformatted default value.
Closes #1008.
> Close #1008. Update HTML.unformatted default value to match js-beautify

- README.md
- appveyor.yml
- examples/nested-jsbeautifyrc/vue/expected/test.vue
- examples/nested-jsbeautifyrc/vue/original/test.vue
- spec/beautify-languages-spec.coffee
- src/beautifiers/index.coffee
- src/beautifiers/vue-beautifier.coffee
- src/languages/index.coffee
- src/languages/vue.coffee
- Add a language `vue`
- Add a beautifier `vue-beautifier`
- Fix AppVeyor CI temporally
---
Related to #1119 and LeslieYQ/vue-format#1, close #722
---
Nope
---
> Implement a basic beautifer for Vue Components

- .travis.yml
- README.md
- appveyor.yml
- docs/options.md
- examples/nested-jsbeautifyrc/sass/expected/test.sass
- examples/nested-jsbeautifyrc/sass/original/test.sass
- package.json
- src/beautifiers/csscomb.coffee
- src/beautifiers/index.coffee
- src/beautifiers/prettydiff.coffee
- src/beautifiers/sass-convert.coffee
- src/languages/sass.coffee
- Add a new beautifier: SassConvert
- Fix Sass beautification
Refer to #1088 for related discussions.
...
#1088
...
This PR is ready for merge.
...
> Fix Sass beautification

- CHANGELOG.md
- docs/options.md
- package.json
- src/beautifiers/prettydiff.coffee
> Add PrettyDiff's bracepadding support

- ISSUE_TEMPLATE.md
This change makes issue reports clearer and easier to understand on first reading or for people who are searching the issues attempting to not file duplicates.
This change does not effect build, test, input, or output of the product.
> Expanded ISSUE_TEMPLATE.md

- src/beautifiers/php-cs-fixer.coffee
Linking to the installation instructions of PHP doens't really help people when working the PHP-CS-Fixer :)
> Link to the official PHP-CS-Fixer repository

- src/languages/fortran.coffee
f95 file extension was added
...
...
> f95 file extension was added

- README.md
- docs/options.md
- package.json
- src/beautifiers/clang-format.coffee
- src/languages/glsl.coffee
- src/languages/index.coffee
Language support for GLSL with clang-format as beautifier
...
No
...
...
> Added language support for GLSL via clang-format

- src/beautifiers/js-beautify.coffee
We will be able to beautify HTML (Angular) Files with JS Beautify
> Add EJS options to JS Beautify

- src/beautifiers/js-beautify.coffee
I would love to use the **language-babel** syntax package and **JS Beautify** together for my **.js** files, this will make it possible!
> Add JSX option to to JS Beautify

- src/beautifiers/hh_format.coffee
- src/beautifiers/index.coffee
Support for hh_format for PHP.
Couldn't find any issues related to hh_format
Haven't added a test as having hh_format installed in CI is a hurdle.
Please let me know if any changes are required.
> Implement hh_format for PHP

- src/languages/nunjucks.coffee
This just removes the console.log from nunjucts.coffee.
https://github.com/Glavin001/atom-beautify/issues/1449
> Fixes #1449, console.log in nunjucts.coffee

- .codeclimate.yml
- codeclimate.yml
This is a Code Climate config with ESLint and Coffeelint enabled. 
...
- No
...
...
> Create Code Climate config

- CHANGELOG.md
- README.md
- package.json
- src/beautifiers/eslint.coffee
- src/beautifiers/index.coffee
Hey guys,
This is an implementation for the ESLint fixer for Javascript.
Let me know if there is any improvement that must be done before it gets merged. I have been using it for a couple of weeks and it's great.
Thanks,
> Add ESLint beautifier

- appveyor.yml
Fix Ruby and PHP install error on Appveyor. 
No.
> Fix appveyor environment settings

- src/languages/cpp.coffee
Adds cuda extensions ".cu" and ".cuh" as extensions of c++ language
...
Yes, my own. https://github.com/Glavin001/atom-beautify/issues/1506
...
...
> Adding CUDA language as extension of C++

- README.md
- docs/options.md
- src/beautifiers/prettydiff.coffee
Adds Pretty Diff as beautifier for Mustache
Closes #1593 
> Add Pretty Diff support for Mustache

- README.md
- docs/options.md
- package.json
- src/beautifiers/prettydiff.coffee
- src/languages/gohtml.coffee
- src/languages/index.coffee
Golang template support
https://github.com/Glavin001/atom-beautify/issues/1190
...
> Golang template support.

- docs/options.md
- src/beautifiers/php-cs-fixer.coffee
- src/languages/php.coffee
Correspondence to PHP-CS-Fixer v2.
#1465 
- This is breaking change for PHP. 💥 
- This PR is subject to #1510 merged.
> Correspondence to PHP-CS-Fixer v2

- README.md
- docs/options.md
- examples/nested-jsbeautifyrc/.jsbeautifyrc
- examples/nested-jsbeautifyrc/yaml/expected/test.yaml
- examples/nested-jsbeautifyrc/yaml/original/test.yaml
- package.json
- src/beautifiers/align-yaml.coffee
- src/beautifiers/index.coffee
- src/languages/index.coffee
- src/languages/yaml.coffee
See #312. Add align-yaml as YAML beautifier
https://github.com/Glavin001/atom-beautify/issues/312
...
> See #312. Add align-yaml as YAML beautifier

- CHANGELOG.md
- package.json
- src/options.json
Updates CSSComb to the latest version (v4.0.1).
...
#1547 and #1630, maybe more.
...
- [N/A] Added examples for testing to [examples/ directory](examples/)
- [Glavin001/atom-beautify is failing on master] AppVeyor passes (Windows support)
> Update CSSComb to v4.0.1.

- src/beautifiers/phpcbf.coffee
fixes #1684
fixes #1487
There's a big if isWin that splits the code and patches keep only happening on the win half. This ports another fix from there to apply to other platforms.
fixes #1684
fixes #1487
(both already closed but don't problem was still happening on MacOS)
> apply #1649 fix to other platforms besides win

- .travis.yml
Fixes Travis builds for Linux and MacOS so they both run without errors.
...
...
https://travis-ci.org/szeck87/atom-beautify/builds/282486310
https://ci.appveyor.com/project/szeck87/atom-beautify/build/32
...
> Add --user for linux pip installs and init opam for MacOS

- .travis.yml
Fixes (hopefully) the Travis MacOS build failure
...
...
...
- [] Regenerate documentation with `npm run docs`
> Add language-puppet to Travis as Atom package install

- README-template.md
- README.md
Instructions for installing atom-beautify
...
...
...
> Update readme template install steps and run npm run docs

- .github/stale.yml
Once this is merged and https://probot.github.io/apps/stale/ is added to the repository, it should start working within an hour.
...
It will close a lot of currently open issues
...
...
> Add stale.yml for Stale probot

- README-template.md
- README.md
- docs/troubleshooting.md
This adds three things:
1. A badge showing the number of downloads from APM to the readme
2. Adds a link to contributing.md on the readme
3. Adds a common issues section to troubleshooting
...
...
Related to #1928.
> Update readme and troubleshooting

- README.md
- docs/options.md
- src/beautifiers/puppet-fix.coffee
- src/options.json
Use unibeautify/puppet-lint that provides puppet-lint in docker.
> Use docker image to run puppet-lint

- README-template.md
- README.md
Add Twitter badge.
[![Twitter URL](https://img.shields.io/twitter/url/http/shields.io.svg?style=social)](https://twitter.com/unibeautify)
No.
No.
> Add Twitter badge

- README-template.md
- README.md
Adds link about Unibeautify Bot to README.
No.
No.
> Add Unibeautify Bot link

- README-template.md
- README.md
Change Unibeautify Bot to Unibeautify CI.
No.
No.
> Unibeautify CI name change

- examples/simple-jsbeautifyrc/tsx/expected/test.tsx
- examples/simple-jsbeautifyrc/tsx/original/test.tsx
- src/beautifiers/typescript-formatter.coffee
Fixes issues introduced with the new TSX language and typescript-formatter.
...
...
...
> Typescript fixes

- CHANGELOG.md
- README.md
- docs/options.md
- examples/nested-jsbeautifyrc/gn/expected/test.gn
- examples/nested-jsbeautifyrc/gn/original/test.gn
- package.json
- src/beautifiers/gn.coffee
- src/beautifiers/index.coffee
- src/languages/gn.coffee
- src/languages/index.coffee
- src/options.json
Add GN language and beautifier
No
> Add GN beautifier

- examples/simple-jsbeautifyrc/lua/expected/test.lua
- src/beautifiers/lua-beautifier/beautifier.coffee
fix lua format bug about indent
#1790 
can update dependencies? it still need node 0.8.x, it is too old.
> Fix #1790. Fix Lua indentation format bug

- README-template.md
- README.md
> Add Slack and Twitter Follow badge to README

- package.json
> fixed: package.json repository compatible with apm and npm

- README-template.md
- README.md
> Add CodePass website link to README
